repos:
- repo: local
  hooks:
  - id: black
    name: black
    language: system
    entry: black .
    types: [python]

  - id: codespell
    name: codespell
    language: system
    entry: codespell
#    args:
#      - "src/"
#      - "tests/"
#      - "*.md"
#      - "*.py"
    types: [python, markdown]
    exclude: ^test_data/

  - id: bandit
    name: bandit
    language: system
    entry: bandit --recursive --skip B101,B105,B324 src  # B101 is assert statements
    types: [python]

  - id: isort
    name: isort
    language: system
    entry: isort
    args: ["--profile", "black", "--filter-files"]
    types: [python]

  - id: pyupgrade
    name: pyupgrade
    language: system
    entry: pyupgrade
    args: ["--keep-runtime-typing", "--py37-plus"]
    types: [python]

# https://flake8.pycqa.org/en/latest/user/using-hooks.html
  - id: flake8
    name: flake8
    language: system
    entry: flake8
    # R505 unnecessary elif after return statement.
    # R506 unnecessary else after raise statement.
    args: ["--ignore=C408,C416,F401,F541,R501,R502,R503,R504,R505,R506,W503",
           "--max-complexity=21", "--max-line-length=162", "--show-source",
           "--statistics"]
    types: [ python ]

 # https://jaredkhan.com/blog/mypy-pre-commit
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    # use your preferred Python version
    # language_version: python3.7
    # additional_dependencies: ["mypy==0.790"]
    types: [python]
    # use require_serial so that script
    # is only called once per commit
    require_serial: true
    # Print the number of files as a sanity-check
    verbose: true

#  - id: pytest
#    name: pytest
#    language: system
#    entry: pytest
##    args:
##      - "--durations=10"
##      - "--ignore=tests/test_wcdimportbot.py"
#    types: [ python ]
