repos:
- repo: local
  hooks:
  - id: black
    name: black
    language: system
    entry: black --check
    types: [python]

#  - id: isort
#    name: isort
#    language: system
#    entry: isort --check-only
#    types: [python]